---
title: "Population"
author: "Daniel Chen"
date: "6/17/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggpubr)
```

```{r}
x <- read_csv("Population.csv", col_types = cols(value = col_character()))
y <- read_csv("Capital.csv", col_types = cols(value = col_character()))
z <- read_csv("Incidents.csv", col_types = cols(value = col_character()))
v <- read_csv("State.csv", col_types = cols(value = col_character()))
w <- read_csv("Population_2010.csv", col_types = cols(value = col_character()))
u <- read_csv("Incidents_2010.csv", col_types = cols(value = col_character()))
t <- bind_cols(y, x) %>% 
  rename(State = value...1, Population_2019 = value...2) %>% 
  arrange(y, by_group = FALSE)

e <- bind_cols(v, z) %>% 
  rename(State = value...1, Crime_rate_2019 = value...2) %>% 
  arrange(v, by_group = FALSE)

c <- bind_cols(t, e) %>% 
  mutate(State = State...1, State...3) %>% 
  select(-State...1, -State...3)
  
a <- bind_cols(y, w) %>% 
   rename(State = value...1, Population_2010 = value...2) %>% 
  arrange(y, by_group = FALSE)

b <- bind_cols(v, u) %>% 
   rename(State = value...1, Crime_rate_2010 = value...2) %>% 
  arrange(y, by_group = FALSE) 

d <- bind_cols(a, b) %>% 
  mutate(State = State...1) %>% 
  select(-State...1, -State...3)

```


```{r}
all_data <- left_join(c, d) %>% 
  mutate(Population_2010 = parse_number(Population_2010)) %>% 
  mutate(Population_2019 = parse_number(Population_2019)) %>% 
  mutate(Population_2010 = Population_2010/1000000) %>% 
  mutate(Population_2019 = Population_2019/1000000) %>% 
  mutate(Crime_rate_2010 = parse_number(Crime_rate_2010)) %>% 
  mutate(Crime_rate_2019 = parse_number(Crime_rate_2019))

pop_data <- all_data %>% 
  select(State, Population_2010, Population_2019) %>% 
  rename("2010" = Population_2010, "2019" = Population_2019) %>% 
    pivot_longer(names_to = "year", values_to = "pop", cols = c("2010", "2019"))

crime_data <- all_data %>% 
  select(State, Crime_rate_2010, Crime_rate_2019) %>% 
    rename("2010" = Crime_rate_2010, "2019" = Crime_rate_2019) %>% 
  pivot_longer(names_to = "year", values_to = "rate", cols = c("2010", "2019")) 

final_data <- inner_join(pop_data, crime_data)
```


```{r}
state_crime <- ggplot(data = final_data, mapping = aes(x = State, y = rate, fill = year))+
  theme(axis.text.x = element_text(angle = 60, hjust = 1))+
  scale_y_continuous()+
  geom_col(position = "dodge")+
  labs(title = "State and Crime rate in 2010 and 2019",
       x = "State",
       y = "Crime Rate")+
  theme(plot.title = element_text(size = 10),
         axis.title.x = element_text(size = 10),
         axis.title.y = element_text(size = 10))

state_pop <- ggplot(data = final_data, mapping = aes(x = State, y = pop, fill = year))+
    theme(axis.text.x = element_text(angle = 60, hjust = 1))+
  scale_y_continuous()+
  geom_col(position = "dodge")+
  labs(title = "State and Population in 2010 and 2019",
       x = "State",
       y = "Population")+
  theme(plot.title = element_text(size = 10),
        axis.title.x = element_text(size = 10),
        axis.title.y = element_text(size = 10))
```


```{r}
rough_graph <- ggarrange(state_crime, state_pop, 
          ncol = 1, nrow = 2)

annotate_figure(rough_graph,
                top = text_grob(""))
```



